# Generated by Django 5.2 on 2026-04-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donor_last_donation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='available',
        ),
    ]
