# Generated by Django 5.2 on 2026-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_donor_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
