# Generated by Django 5.2 on 2026-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
