# Generated by Django 5.2 on 2026-04-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donor_is_verified_donor_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
