# Generated by Django 5.2 on 2026-04-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donor_otp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='otp_created_at',
        ),
    ]
