# Generated by Django 5.2 on 2026-04-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bloodrequest_created_at_bloodrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.donor'),
        ),
    ]
